// <auto-generated />
using System;
using MealTimes.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealTimes.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealTimes.Core.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MealTimes.Core.Models.BusinessMetrics", b =>
                {
                    b.Property<int>("MetricsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MetricsID"));

                    b.Property<int>("ActiveChefs")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("ActiveSubscriptions")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageOrderValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ChefPayouts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CommissionRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("NetProfit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OperationalCosts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ProfitMargin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("SubscriptionRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalExpenses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MetricsID");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("BusinessMetrics");
                });

            modelBuilder.Entity("MealTimes.Core.Models.ChefPayout", b =>
                {
                    b.Property<int>("PayoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PayoutID"));

                    b.Property<int>("ChefID")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionDeducted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PayableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayoutPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PayoutID");

                    b.HasIndex("Status");

                    b.HasIndex("ChefID", "PeriodStart", "PeriodEnd");

                    b.ToTable("ChefPayouts");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Commission", b =>
                {
                    b.Property<int>("CommissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommissionID"));

                    b.Property<int>("ChefID")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChefPayableAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ChefPayoutPayoutID")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<decimal>("PlatformEarning")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("CommissionID");

                    b.HasIndex("ChefPayoutPayoutID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("ChefID", "CreatedAt");

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("MealTimes.Core.Models.CompanySubscriptionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorporateCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SubscribedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SubscriptionPlanID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorporateCompanyId");

                    b.HasIndex("SubscriptionPlanID");

                    b.ToTable("CompanySubscriptionHistories");
                });

            modelBuilder.Entity("MealTimes.Core.Models.CorporateCompany", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyID"));

                    b.Property<int?>("ActiveSubscriptionPlanID")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AdminID")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PlanEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PlanStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SubscriptionPlanID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("CompanyID");

                    b.HasIndex("ActiveSubscriptionPlanID");

                    b.HasIndex("AdminID");

                    b.HasIndex("LocationID");

                    b.HasIndex("SubscriptionPlanID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("CorporateCompanies");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryID"));

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeliveryPersonID")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DeliveryID");

                    b.HasIndex("DeliveryPersonID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("MealTimes.Core.Models.DeliveryPerson", b =>
                {
                    b.Property<int>("DeliveryPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryPersonID"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleInfo")
                        .HasColumnType("text");

                    b.HasKey("DeliveryPersonID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("DeliveryPersons");
                });

            modelBuilder.Entity("MealTimes.Core.Models.DietaryPreference", b =>
                {
                    b.Property<int>("DietaryPreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DietaryPreferenceID"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DietaryPreferenceID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.ToTable("DietaryPreferences");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("DietaryPreferences")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("LocationID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("FeedbackID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("OrderID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("MealTimes.Core.Models.HomeChef", b =>
                {
                    b.Property<int>("ChefID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChefID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ChefID");

                    b.HasIndex("LocationID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("HomeChefs");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationID"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("LocationID");

                    b.HasIndex("City");

                    b.HasIndex("State");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealID"));

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<int>("ChefID")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("MealID");

                    b.HasIndex("ChefID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<int>("ChefID")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderID");

                    b.HasIndex("ChefID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MealTimes.Core.Models.OrderMeal", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.Property<int>("MealID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderID", "MealID");

                    b.HasIndex("MealID");

                    b.ToTable("OrderMeals");
                });

            modelBuilder.Entity("MealTimes.Core.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Token", "IsUsed", "ExpiresAt");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentID"));

                    b.Property<int?>("CorporateCompanyID")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderID")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("text");

                    b.Property<int?>("SubscriptionPlanID")
                        .HasColumnType("integer");

                    b.HasKey("PaymentID");

                    b.HasIndex("CorporateCompanyID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("SubscriptionPlanID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MealTimes.Core.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("SubscriptionPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionPlanID"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("MealLimitPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubscriptionPlanID");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("MealTimes.Core.Models.ThirdPartyDeliveryService", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryID"));

                    b.Property<string>("DeliveryPartnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EstimatedDeliveryTime")
                        .HasColumnType("interval");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("ThirdPartyDeliveryServices");
                });

            modelBuilder.Entity("MealTimes.Core.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Admin", b =>
                {
                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("MealTimes.Core.Models.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.ChefPayout", b =>
                {
                    b.HasOne("MealTimes.Core.Models.HomeChef", "Chef")
                        .WithMany()
                        .HasForeignKey("ChefID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chef");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Commission", b =>
                {
                    b.HasOne("MealTimes.Core.Models.HomeChef", "Chef")
                        .WithMany()
                        .HasForeignKey("ChefID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.ChefPayout", null)
                        .WithMany("Commissions")
                        .HasForeignKey("ChefPayoutPayoutID");

                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithOne()
                        .HasForeignKey("MealTimes.Core.Models.Commission", "OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealTimes.Core.Models.CompanySubscriptionHistory", b =>
                {
                    b.HasOne("MealTimes.Core.Models.CorporateCompany", "CorporateCompany")
                        .WithMany()
                        .HasForeignKey("CorporateCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorporateCompany");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("MealTimes.Core.Models.CorporateCompany", b =>
                {
                    b.HasOne("MealTimes.Core.Models.SubscriptionPlan", "ActiveSubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("ActiveSubscriptionPlanID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealTimes.Core.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealTimes.Core.Models.Location", "Location")
                        .WithMany("CorporateCompanies")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealTimes.Core.Models.SubscriptionPlan", null)
                        .WithMany("CompaniesUsingThisPlan")
                        .HasForeignKey("SubscriptionPlanID");

                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithOne("CorporateCompany")
                        .HasForeignKey("MealTimes.Core.Models.CorporateCompany", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActiveSubscriptionPlan");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Delivery", b =>
                {
                    b.HasOne("MealTimes.Core.Models.DeliveryPerson", "DeliveryPerson")
                        .WithMany("Deliveries")
                        .HasForeignKey("DeliveryPersonID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("MealTimes.Core.Models.Delivery", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPerson");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealTimes.Core.Models.DeliveryPerson", b =>
                {
                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithOne("DeliveryPerson")
                        .HasForeignKey("MealTimes.Core.Models.DeliveryPerson", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.DietaryPreference", b =>
                {
                    b.HasOne("MealTimes.Core.Models.Employee", "Employee")
                        .WithOne("DietaryPreference")
                        .HasForeignKey("MealTimes.Core.Models.DietaryPreference", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Employee", b =>
                {
                    b.HasOne("MealTimes.Core.Models.CorporateCompany", "CorporateCompany")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("MealTimes.Core.Models.Employee", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorporateCompany");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Feedback", b =>
                {
                    b.HasOne("MealTimes.Core.Models.Employee", "Employee")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealTimes.Core.Models.HomeChef", b =>
                {
                    b.HasOne("MealTimes.Core.Models.Location", "Location")
                        .WithMany("HomeChefs")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithOne("HomeChef")
                        .HasForeignKey("MealTimes.Core.Models.HomeChef", "UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Meal", b =>
                {
                    b.HasOne("MealTimes.Core.Models.HomeChef", "Chef")
                        .WithMany("Meals")
                        .HasForeignKey("ChefID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Order", b =>
                {
                    b.HasOne("MealTimes.Core.Models.HomeChef", "Chef")
                        .WithMany("Orders")
                        .HasForeignKey("ChefID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MealTimes.Core.Models.OrderMeal", b =>
                {
                    b.HasOne("MealTimes.Core.Models.Meal", "Meal")
                        .WithMany("OrderMeals")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithMany("OrderMeals")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealTimes.Core.Models.PasswordResetToken", b =>
                {
                    b.HasOne("MealTimes.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Payment", b =>
                {
                    b.HasOne("MealTimes.Core.Models.CorporateCompany", "CorporateCompany")
                        .WithMany()
                        .HasForeignKey("CorporateCompanyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("MealTimes.Core.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MealTimes.Core.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CorporateCompany");

                    b.Navigation("Order");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("MealTimes.Core.Models.ThirdPartyDeliveryService", b =>
                {
                    b.HasOne("MealTimes.Core.Models.Order", "Order")
                        .WithOne("ThirdPartyDeliveryService")
                        .HasForeignKey("MealTimes.Core.Models.ThirdPartyDeliveryService", "OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealTimes.Core.Models.ChefPayout", b =>
                {
                    b.Navigation("Commissions");
                });

            modelBuilder.Entity("MealTimes.Core.Models.CorporateCompany", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MealTimes.Core.Models.DeliveryPerson", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Employee", b =>
                {
                    b.Navigation("DietaryPreference")
                        .IsRequired();

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MealTimes.Core.Models.HomeChef", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Location", b =>
                {
                    b.Navigation("CorporateCompanies");

                    b.Navigation("Employees");

                    b.Navigation("HomeChefs");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Meal", b =>
                {
                    b.Navigation("OrderMeals");
                });

            modelBuilder.Entity("MealTimes.Core.Models.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("Feedbacks");

                    b.Navigation("OrderMeals");

                    b.Navigation("Payment");

                    b.Navigation("ThirdPartyDeliveryService");
                });

            modelBuilder.Entity("MealTimes.Core.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("CompaniesUsingThisPlan");
                });

            modelBuilder.Entity("MealTimes.Core.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("CorporateCompany");

                    b.Navigation("DeliveryPerson");

                    b.Navigation("Employee");

                    b.Navigation("HomeChef");
                });
#pragma warning restore 612, 618
        }
    }
}
